export const SLUGIFY = 'SLUGIFY';
export const REMOVE_CHARACTERS = 'REMOVE_CHARACTERS';
export const APPEND_CHARACTERS = 'APPEND_CHARACTERS';
export const UPPER_CASE = 'UPPER_CASE';
export const LOWER_CASE = 'LOWER_CASE';
