export const ADD_TRANSFORM = 'ADD_TRANSFORM';
export const CHANGE_TRANSFORM = 'CHANGE_TRANSFORM';
export const REMOVE_TRANSFORM = 'REMOVE_TRANSFORM';
export const ADD_FILE = 'ADD_FILE';
export const RENAME_FILES = 'RENAME_FILES';
export const REMOVE_FILE = 'REMOVE_FILE';
export const CLEAR_FILES = 'CLEAR_FILES';

export const CHANGE_POSITION = 'CHANGE_POSITION';
